In [32]:
import pandas  as pd
import numpy as np
from sklearn.model_selection import GridSearchCV

In [33]:
dataset=pd.read_csv("CKD.csv")

In [34]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [35]:
num = dataset.select_dtypes(include= ['number']).columns.to_list()
cat = dataset.select_dtypes(include= ['category','object']).columns.to_list()
#print(num)
print(cat)

['sg', 'rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane', 'classification']

In [36]:
dataset=pd.get_dummies(dataset,drop_first="True")

In [37]:
dataset.shape

(399, 28)

In [38]:
input=dataset.drop(columns=["classification_yes"])

In [39]:
input

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,False,False,False,False,True,True,False
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,True,False,False,False,False,False,True,False,False
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,True,False,False,False,False,False,True,False,False
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,True,False,False,False,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,True,False,False,False,False,False,True,False,False
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,True,False,False,True,True,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,True,False,False,True,True,False,False,False,False
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,True,False,False,True,True,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,True,False,False,False,False,False,True,False,False

In [40]:
dataset[num].isna().sum()

age     0
bp      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hrmo    0
pcv     0
wc      0
rc      0
dtype: int64

In [41]:
output=dataset["classification_yes"]

In [12]:
print(output)

0       True
1       True
2       True
3       True
4       True
       ...
394     True
395     True
396     True
397     True
398    False
Name: classification_yes, Length: 399, dtype: bool

In [42]:
from sklearn.model_selection import train_test_split
#from sklearn.model_selection import train_test_split

In [43]:
x_train,x_test,y_train,y_test=train_test_split(input,output,test_size=1/3,random_state=0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [47]:
#from sklearn.ensemble import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

In [48]:
from sklearn.model_selection import GridSearchCV
params = {
    'max_depth': [5, 10, 20,25],
    'min_samples_leaf': [10, 20, 50, 100,120],
    'criterion': ["gini", "entropy"]
}


grid = GridSearchCV(estimator=DecisionTreeClassifier(), 
                           param_grid=params, 
                           n_jobs=-1, verbose=1, scoring = "accuracy")


# fitting the model for grid search 
grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [5, 10, 20, 25],
                         'min_samples_leaf': [10, 20, 50, 100, 120]},
             scoring='accuracy', verbose=1)

In [49]:
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(x_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [50]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 20}: 0.9177041983841591

In [51]:
print(cm)

[[47  4]
 [ 7 75]]

In [52]:
from sklearn.metrics import classification_report

In [53]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

       False       0.87      0.92      0.90        51
        True       0.95      0.91      0.93        82

    accuracy                           0.92       133
   macro avg       0.91      0.92      0.91       133
weighted avg       0.92      0.92      0.92       133

In [54]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9747728359636537

In [55]:
table=pd.DataFrame.from_dict(re)

In [27]:
print(table)

     mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         1.990861      0.839141         0.116925        0.056839
1         3.294219      0.784448         0.179995        0.081321
2         4.950632      0.938523         0.292384        0.108764
3         1.799140      0.382625         0.114913        0.054856
4         3.612698      1.277042         0.280490        0.175545
..             ...           ...              ...             ...
211       3.127027      0.502998         0.227886        0.130866
212       4.301918      1.264506         0.337011        0.186877
213       1.696595      0.269206         0.136253        0.068589
214       2.447217      0.659140         0.207425        0.112280
215       3.500685      0.704923         0.200925        0.043861

    param_bootstrap param_max_depth param_max_features param_min_samples_leaf  \
0              True            None               log2                      1
1              True            None               log2                      1
2              True            None               log2                      1
3              True            None               log2                      1
4              True            None               log2                      1
..              ...             ...                ...                    ...
211           False             100               sqrt                      4
212           False             100               sqrt                      4
213           False             100               sqrt                      4
214           False             100               sqrt                      4
215           False             100               sqrt                      4

    param_min_samples_split param_n_estimators  \
0                         2                200
1                         2                400
2                         2                600
3                         5                200
4                         5                400
..                      ...                ...
211                       5                400
212                       5                600
213                      10                200
214                      10                400
215                      10                600

                                                params  split0_test_score  \
0    {'bootstrap': True, 'max_depth': None, 'max_fe...           1.000000
1    {'bootstrap': True, 'max_depth': None, 'max_fe...           1.000000
2    {'bootstrap': True, 'max_depth': None, 'max_fe...           1.000000
3    {'bootstrap': True, 'max_depth': None, 'max_fe...           1.000000
4    {'bootstrap': True, 'max_depth': None, 'max_fe...           1.000000
..                                                 ...                ...
211  {'bootstrap': False, 'max_depth': 100, 'max_fe...           0.962963
212  {'bootstrap': False, 'max_depth': 100, 'max_fe...           0.944444
213  {'bootstrap': False, 'max_depth': 100, 'max_fe...           0.944444
214  {'bootstrap': False, 'max_depth': 100, 'max_fe...           0.962963
215  {'bootstrap': False, 'max_depth': 100, 'max_fe...           0.981481

     split1_test_score  split2_test_score  split3_test_score  \
0             0.943396           0.981132           0.962264
1             0.962264           0.981132           0.962264
2             0.962264           0.981132           0.981132
3             0.943396           0.981132           0.981132
4             0.943396           0.981132           0.981132
..                 ...                ...                ...
211           0.943396           0.943396           0.981132
212           0.943396           0.943396           0.981132
213           0.943396           0.943396           0.962264
214           0.943396           0.943396           0.981132
215           0.943396           0.943396           0.981132

     split4_test_score  mean_test_score  std_test_score  rank_test_score
0             0.981132         0.973585        0.019242               58
1             1.000000         0.981132        0.016876                5
2             0.981132         0.981132        0.011933                5
3             0.981132         0.977358        0.018487               26
4             0.981132         0.977358        0.018487               26
..                 ...              ...             ...              ...
211           0.981132         0.962404        0.016878              173
212           0.981132         0.958700        0.018320              196
213           0.981132         0.954927        0.014942              215
214           0.981132         0.962404        0.016878              173
215           0.981132         0.966108        0.018544              150

[216 rows x 19 columns]